default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
exclude: |
  (?x)(
      ^docs/.*.html|
      ^inst/extdata|
      ^man/|
      ^tests/testthat/_snaps/
   )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=12000"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # spell check
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args: ["--ignore-words-list=entrace"]
  # R formatting
  - repo: https://github.com/posit-dev/air-pre-commit
    rev: 0.11.0
    hooks:
      - id: air-format
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9029
    hooks:
      - id: parsable-R
      - id: use-tidy-description
      - id: lintr
        args: [--warn_only]
        verbose: true
  # enforce commit format
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
