ml_methods = ['regLogistic', 'rf']
seeds = range(100, 101)

rule targets:
    input:
        expand("results/runs/{method}_{seed}_full.Rds", method = ml_methods, seed = seeds)

rule preprocess_data:
    input:
        R="code/preproc.R",
        csv="data/raw/otu_medium.csv"
    output:
        rds='data/processed/otu_medium.Rds'
    script:
        "{input.R}"

rule run_ml:
    input:
        R="code/ml.R",
        rds=rules.preprocess_data.output.rds
    output:
        rds="results/runs/{method}_{seed}_full.Rds",
        csv="results/runs/{method}_{seed}_abbrv.csv"
    params:
        method="{method}",
        seed="{seed}"
    resources:
        ncores=8,
        pmem_gb=2
    script:
        "{input.R}"

rule merge_results:
    input:
        R="code/merge_results.R"
        csv=expand("results/runs/{method}_{seed}_abbrv.csv", method = ml_methods, seed = seeds)
    output:
        csv='results/all_results.csv'
    script:
        "{input.R}"


# TODO; plots, report, etc.