name: auto-format

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      R_CHECK_DONTTEST_EXAMPLES: false
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: Suggests

      - name: Document
        run: |
          roxygen2::roxygenize()
        shell: Rscript {0}

      - name: Style
        run: |
          usethis::use_tidy_style()
        shell: Rscript {0}
      - name: Render README
        run: |
          rmarkdown::render("README.Rmd")
        shell: Rscript {0}
      - name: format
        uses: pre-commit/action@v3.0.1
        continue-on-error: true
      - name: commit & push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ci: 🤖 auto-format" && git push || echo "nothing to commit"
